// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const analyticsActivityHourDistribution = `-- name: AnalyticsActivityHourDistribution :many
WITH hourly AS (
    SELECT EXTRACT(HOUR FROM batch_start_at AT TIME ZONE 'UTC')::int AS hr, COUNT(*) AS cnt
    FROM analytics_visit_batches
    GROUP BY 1
),
tot AS (SELECT COALESCE(SUM(cnt), 0)::float8 AS total FROM hourly)
SELECT hourly.hr AS hour_utc,
       CASE WHEN tot.total = 0 THEN 0::float8
       ELSE 100.0 * hourly.cnt::float8 / tot.total END::float8 AS share_percent
FROM hourly CROSS JOIN tot
ORDER BY hourly.hr
`

type AnalyticsActivityHourDistributionRow struct {
	HourUtc      int32
	SharePercent float64
}

func (q *Queries) AnalyticsActivityHourDistribution(ctx context.Context) ([]AnalyticsActivityHourDistributionRow, error) {
	rows, err := q.db.Query(ctx, analyticsActivityHourDistribution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalyticsActivityHourDistributionRow
	for rows.Next() {
		var i AnalyticsActivityHourDistributionRow
		if err := rows.Scan(&i.HourUtc, &i.SharePercent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsAvgDurations = `-- name: AnalyticsAvgDurations :one
SELECT
    COALESCE(AVG(active_duration_ms), 0)::double precision AS avg_active_ms,
    COALESCE(AVG(visible_duration_ms), 0)::double precision AS avg_visible_ms,
    COALESCE(MAX(active_duration_ms), 0)::bigint AS max_active_ms
FROM analytics_visit_batches
`

type AnalyticsAvgDurationsRow struct {
	AvgActiveMs  float64
	AvgVisibleMs float64
	MaxActiveMs  int64
}

func (q *Queries) AnalyticsAvgDurations(ctx context.Context) (AnalyticsAvgDurationsRow, error) {
	row := q.db.QueryRow(ctx, analyticsAvgDurations)
	var i AnalyticsAvgDurationsRow
	err := row.Scan(&i.AvgActiveMs, &i.AvgVisibleMs, &i.MaxActiveMs)
	return i, err
}

const analyticsCommentsActivityByDay = `-- name: AnalyticsCommentsActivityByDay :many
SELECT DATE(created_at) AS day, COUNT(*)::bigint AS comments_count
FROM comments
GROUP BY day
ORDER BY day
`

type AnalyticsCommentsActivityByDayRow struct {
	Day           pgtype.Date
	CommentsCount int64
}

func (q *Queries) AnalyticsCommentsActivityByDay(ctx context.Context) ([]AnalyticsCommentsActivityByDayRow, error) {
	rows, err := q.db.Query(ctx, analyticsCommentsActivityByDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalyticsCommentsActivityByDayRow
	for rows.Next() {
		var i AnalyticsCommentsActivityByDayRow
		if err := rows.Scan(&i.Day, &i.CommentsCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsConnectionDensity = `-- name: AnalyticsConnectionDensity :one
SELECT
    COALESCE(
        (SELECT COUNT(*)::double precision FROM comments) / NULLIF((
        SELECT COUNT(*)::double precision FROM (
            SELECT user_id FROM comments
            UNION
            SELECT user_id FROM posts
        ) AS u
    ), 0.0),
    0.0
    )::double precision AS density
`

func (q *Queries) AnalyticsConnectionDensity(ctx context.Context) (float64, error) {
	row := q.db.QueryRow(ctx, analyticsConnectionDensity)
	var density float64
	err := row.Scan(&density)
	return density, err
}

const analyticsDropoffPercent = `-- name: AnalyticsDropoffPercent :one
WITH user_stats AS (
    SELECT user_id,
           COUNT(*) AS post_count,
           MAX(created_at) AS last_post_at
    FROM comments
    GROUP BY user_id
),
eligible AS (
    SELECT user_id, post_count, last_post_at FROM user_stats WHERE post_count >= $2::int
)
SELECT
    CASE WHEN COUNT(*) = 0 THEN 0::float8
    ELSE 100.0 * COUNT(*) FILTER (
        WHERE last_post_at < NOW() - ($1::int * INTERVAL '1 day')
    )::float8 / COUNT(*)::float8
    END::float8 AS churn_percent
FROM eligible
`

type AnalyticsDropoffPercentParams struct {
	InactiveDays int32
	ThresholdN   int32
}

func (q *Queries) AnalyticsDropoffPercent(ctx context.Context, arg AnalyticsDropoffPercentParams) (float64, error) {
	row := q.db.QueryRow(ctx, analyticsDropoffPercent, arg.InactiveDays, arg.ThresholdN)
	var churn_percent float64
	err := row.Scan(&churn_percent)
	return churn_percent, err
}

const analyticsMobileSessionShares = `-- name: AnalyticsMobileSessionShares :one
SELECT
    CASE WHEN COUNT(*) FILTER (WHERE had_read_activity) = 0 THEN 0::float8
    ELSE 100.0 * COUNT(*) FILTER (WHERE had_read_activity AND is_mobile)::float8
         / COUNT(*) FILTER (WHERE had_read_activity)::float8
    END::float8 AS pct_mobile_readers,
    CASE WHEN COUNT(*) FILTER (WHERE had_compose_activity) = 0 THEN 0::float8
    ELSE 100.0 * COUNT(*) FILTER (WHERE had_compose_activity AND is_mobile)::float8
         / COUNT(*) FILTER (WHERE had_compose_activity)::float8
    END::float8 AS pct_mobile_writers,
    CASE WHEN COUNT(*) = 0 THEN 0::float8
    ELSE 100.0 * COUNT(*) FILTER (WHERE is_mobile)::float8 / COUNT(*)::float8
    END::float8 AS pct_mobile_sessions
FROM analytics_visit_batches
`

type AnalyticsMobileSessionSharesRow struct {
	PctMobileReaders  float64
	PctMobileWriters  float64
	PctMobileSessions float64
}

func (q *Queries) AnalyticsMobileSessionShares(ctx context.Context) (AnalyticsMobileSessionSharesRow, error) {
	row := q.db.QueryRow(ctx, analyticsMobileSessionShares)
	var i AnalyticsMobileSessionSharesRow
	err := row.Scan(&i.PctMobileReaders, &i.PctMobileWriters, &i.PctMobileSessions)
	return i, err
}

const analyticsMobileUserPercent = `-- name: AnalyticsMobileUserPercent :one
WITH u AS (
    SELECT user_id, BOOL_OR(is_mobile) AS used_mobile
    FROM analytics_visit_batches
    WHERE user_id IS NOT NULL
    GROUP BY user_id
)
SELECT
    CASE WHEN COUNT(*) = 0 THEN 0::float8
    ELSE 100.0 * COUNT(*) FILTER (WHERE used_mobile)::float8 / COUNT(*)::float8
    END::float8 AS pct_users_with_mobile
FROM u
`

func (q *Queries) AnalyticsMobileUserPercent(ctx context.Context) (float64, error) {
	row := q.db.QueryRow(ctx, analyticsMobileUserPercent)
	var pct_users_with_mobile float64
	err := row.Scan(&pct_users_with_mobile)
	return pct_users_with_mobile, err
}

const analyticsPopularTagsByPostCount = `-- name: AnalyticsPopularTagsByPostCount :many
SELECT tag, COUNT(*)::bigint AS post_count
FROM post_tags
GROUP BY tag
ORDER BY post_count DESC, tag ASC
`

type AnalyticsPopularTagsByPostCountRow struct {
	Tag       string
	PostCount int64
}

func (q *Queries) AnalyticsPopularTagsByPostCount(ctx context.Context) ([]AnalyticsPopularTagsByPostCountRow, error) {
	rows, err := q.db.Query(ctx, analyticsPopularTagsByPostCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalyticsPopularTagsByPostCountRow
	for rows.Next() {
		var i AnalyticsPopularTagsByPostCountRow
		if err := rows.Scan(&i.Tag, &i.PostCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsTopPostInRange = `-- name: AnalyticsTopPostInRange :one
SELECT t.id, t.title, COUNT(c.id)::bigint AS reply_count_in_range
FROM posts t
LEFT JOIN comments c ON c.post_id = t.id
    AND c.created_at >= $1
    AND c.created_at < $2
GROUP BY t.id, t.title
ORDER BY reply_count_in_range DESC, t.id ASC
LIMIT 1
`

type AnalyticsTopPostInRangeParams struct {
	StartAt pgtype.Timestamptz
	EndAt   pgtype.Timestamptz
}

type AnalyticsTopPostInRangeRow struct {
	ID                int32
	Title             string
	ReplyCountInRange int64
}

func (q *Queries) AnalyticsTopPostInRange(ctx context.Context, arg AnalyticsTopPostInRangeParams) (AnalyticsTopPostInRangeRow, error) {
	row := q.db.QueryRow(ctx, analyticsTopPostInRange, arg.StartAt, arg.EndAt)
	var i AnalyticsTopPostInRangeRow
	err := row.Scan(&i.ID, &i.Title, &i.ReplyCountInRange)
	return i, err
}

const analyticsTopTag = `-- name: AnalyticsTopTag :one
SELECT tag, COUNT(*)::bigint AS usage_count
FROM post_tags
GROUP BY tag
ORDER BY usage_count DESC, tag ASC
LIMIT 1
`

type AnalyticsTopTagRow struct {
	Tag        string
	UsageCount int64
}

func (q *Queries) AnalyticsTopTag(ctx context.Context) (AnalyticsTopTagRow, error) {
	row := q.db.QueryRow(ctx, analyticsTopTag)
	var i AnalyticsTopTagRow
	err := row.Scan(&i.Tag, &i.UsageCount)
	return i, err
}

const analyticsTopUsersByComments = `-- name: AnalyticsTopUsersByComments :many
SELECT u.id, u.name, COUNT(c.id)::bigint AS comment_count
FROM users u
JOIN comments c ON u.id = c.user_id
GROUP BY u.id, u.name
ORDER BY comment_count DESC, u.id ASC
LIMIT 10
`

type AnalyticsTopUsersByCommentsRow struct {
	ID           int32
	Name         string
	CommentCount int64
}

func (q *Queries) AnalyticsTopUsersByComments(ctx context.Context) ([]AnalyticsTopUsersByCommentsRow, error) {
	rows, err := q.db.Query(ctx, analyticsTopUsersByComments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalyticsTopUsersByCommentsRow
	for rows.Next() {
		var i AnalyticsTopUsersByCommentsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.CommentCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsTopUsersByPosts = `-- name: AnalyticsTopUsersByPosts :many
SELECT u.id, u.name, COUNT(t.id)::bigint AS post_count
FROM users u
JOIN posts t ON u.id = t.user_id
GROUP BY u.id, u.name
ORDER BY post_count DESC, u.id ASC
`

type AnalyticsTopUsersByPostsRow struct {
	ID        int32
	Name      string
	PostCount int64
}

func (q *Queries) AnalyticsTopUsersByPosts(ctx context.Context) ([]AnalyticsTopUsersByPostsRow, error) {
	rows, err := q.db.Query(ctx, analyticsTopUsersByPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalyticsTopUsersByPostsRow
	for rows.Next() {
		var i AnalyticsTopUsersByPostsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.PostCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsUsersWithCommentsButNoPosts = `-- name: AnalyticsUsersWithCommentsButNoPosts :many
SELECT u.id, u.name, COUNT(c.id)::bigint AS comment_count
FROM users u
JOIN comments c ON u.id = c.user_id
LEFT JOIN posts t ON u.id = t.user_id
WHERE t.id IS NULL
GROUP BY u.id, u.name
ORDER BY comment_count DESC, u.id ASC
`

type AnalyticsUsersWithCommentsButNoPostsRow struct {
	ID           int32
	Name         string
	CommentCount int64
}

func (q *Queries) AnalyticsUsersWithCommentsButNoPosts(ctx context.Context) ([]AnalyticsUsersWithCommentsButNoPostsRow, error) {
	rows, err := q.db.Query(ctx, analyticsUsersWithCommentsButNoPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalyticsUsersWithCommentsButNoPostsRow
	for rows.Next() {
		var i AnalyticsUsersWithCommentsButNoPostsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.CommentCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsVisitBatchInsert = `-- name: AnalyticsVisitBatchInsert :exec
INSERT INTO analytics_visit_batches (
    user_id, client_batch_id, active_duration_ms, visible_duration_ms,
    is_mobile, had_compose_activity, had_read_activity, batch_start_at, batch_end_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (client_batch_id) DO NOTHING
`

type AnalyticsVisitBatchInsertParams struct {
	UserID             pgtype.Int4
	ClientBatchID      pgtype.UUID
	ActiveDurationMs   int64
	VisibleDurationMs  int64
	IsMobile           bool
	HadComposeActivity bool
	HadReadActivity    bool
	BatchStartAt       pgtype.Timestamptz
	BatchEndAt         pgtype.Timestamptz
}

func (q *Queries) AnalyticsVisitBatchInsert(ctx context.Context, arg AnalyticsVisitBatchInsertParams) error {
	_, err := q.db.Exec(ctx, analyticsVisitBatchInsert,
		arg.UserID,
		arg.ClientBatchID,
		arg.ActiveDurationMs,
		arg.VisibleDurationMs,
		arg.IsMobile,
		arg.HadComposeActivity,
		arg.HadReadActivity,
		arg.BatchStartAt,
		arg.BatchEndAt,
	)
	return err
}

const authCreate = `-- name: AuthCreate :exec
INSERT INTO auth_passwords (user_id, login, password_hash) VALUES ($1, $2, $3)
`

type AuthCreateParams struct {
	UserID       int32
	Login        string
	PasswordHash string
}

func (q *Queries) AuthCreate(ctx context.Context, arg AuthCreateParams) error {
	_, err := q.db.Exec(ctx, authCreate, arg.UserID, arg.Login, arg.PasswordHash)
	return err
}

const authCreateSession = `-- name: AuthCreateSession :exec
INSERT INTO sessions (session_id, user_id) VALUES ($1, $2)
`

type AuthCreateSessionParams struct {
	SessionID pgtype.UUID
	UserID    int32
}

func (q *Queries) AuthCreateSession(ctx context.Context, arg AuthCreateSessionParams) error {
	_, err := q.db.Exec(ctx, authCreateSession, arg.SessionID, arg.UserID)
	return err
}

const authDeleteAllUserSessions = `-- name: AuthDeleteAllUserSessions :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) AuthDeleteAllUserSessions(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, authDeleteAllUserSessions, userID)
	return err
}

const authDeleteSession = `-- name: AuthDeleteSession :exec
DELETE FROM sessions WHERE session_id = $1
`

func (q *Queries) AuthDeleteSession(ctx context.Context, sessionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, authDeleteSession, sessionID)
	return err
}

const authGetUserAndPasswordHash = `-- name: AuthGetUserAndPasswordHash :one
SELECT user_id, password_hash FROM auth_passwords WHERE login = $1
`

type AuthGetUserAndPasswordHashRow struct {
	UserID       int32
	PasswordHash string
}

func (q *Queries) AuthGetUserAndPasswordHash(ctx context.Context, login string) (AuthGetUserAndPasswordHashRow, error) {
	row := q.db.QueryRow(ctx, authGetUserAndPasswordHash, login)
	var i AuthGetUserAndPasswordHashRow
	err := row.Scan(&i.UserID, &i.PasswordHash)
	return i, err
}

const authGetUserIDBySessionID = `-- name: AuthGetUserIDBySessionID :one
SELECT user_id FROM sessions WHERE session_id = $1
`

func (q *Queries) AuthGetUserIDBySessionID(ctx context.Context, sessionID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, authGetUserIDBySessionID, sessionID)
	var user_id int32
	err := row.Scan(&user_id)
	return user_id, err
}

const authUpdatePassword = `-- name: AuthUpdatePassword :exec
UPDATE auth_passwords SET password_hash = $2 WHERE user_id = $1
`

type AuthUpdatePasswordParams struct {
	UserID       int32
	PasswordHash string
}

func (q *Queries) AuthUpdatePassword(ctx context.Context, arg AuthUpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, authUpdatePassword, arg.UserID, arg.PasswordHash)
	return err
}

const commentCreate = `-- name: CommentCreate :one
INSERT INTO comments (post_id, user_id, content) VALUES ($1, $2, $3)
RETURNING id, post_id, user_id, content, created_at
`

type CommentCreateParams struct {
	PostID  int32
	UserID  int32
	Content string
}

type CommentCreateRow struct {
	ID        int32
	PostID    int32
	UserID    int32
	Content   string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CommentCreate(ctx context.Context, arg CommentCreateParams) (CommentCreateRow, error) {
	row := q.db.QueryRow(ctx, commentCreate, arg.PostID, arg.UserID, arg.Content)
	var i CommentCreateRow
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const commentListByPostId = `-- name: CommentListByPostId :many
SELECT id, post_id, user_id, content, created_at FROM comments
WHERE post_id = $1 ORDER BY created_at DESC
`

type CommentListByPostIdRow struct {
	ID        int32
	PostID    int32
	UserID    int32
	Content   string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CommentListByPostId(ctx context.Context, postID int32) ([]CommentListByPostIdRow, error) {
	rows, err := q.db.Query(ctx, commentListByPostId, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommentListByPostIdRow
	for rows.Next() {
		var i CommentListByPostIdRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const postCreate = `-- name: PostCreate :one
INSERT INTO posts (title, content, user_id, comments_count) VALUES ($1, $2, $3, 0)
RETURNING id, title, content, comments_count, user_id, created_at
`

type PostCreateParams struct {
	Title   string
	Content string
	UserID  int32
}

type PostCreateRow struct {
	ID            int32
	Title         string
	Content       string
	CommentsCount int32
	UserID        int32
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) PostCreate(ctx context.Context, arg PostCreateParams) (PostCreateRow, error) {
	row := q.db.QueryRow(ctx, postCreate, arg.Title, arg.Content, arg.UserID)
	var i PostCreateRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CommentsCount,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const postGetById = `-- name: PostGetById :one
SELECT id, title, content, user_id, comments_count, created_at FROM posts WHERE id = $1
`

type PostGetByIdRow struct {
	ID            int32
	Title         string
	Content       string
	UserID        int32
	CommentsCount int32
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) PostGetById(ctx context.Context, id int32) (PostGetByIdRow, error) {
	row := q.db.QueryRow(ctx, postGetById, id)
	var i PostGetByIdRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.UserID,
		&i.CommentsCount,
		&i.CreatedAt,
	)
	return i, err
}

const postPageByPageID = `-- name: PostPageByPageID :many
SELECT id, title, content, user_id, comments_count, created_at
FROM posts
ORDER BY id DESC LIMIT $1 OFFSET $2
`

type PostPageByPageIDParams struct {
	Limit  int32
	Offset int32
}

type PostPageByPageIDRow struct {
	ID            int32
	Title         string
	Content       string
	UserID        int32
	CommentsCount int32
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) PostPageByPageID(ctx context.Context, arg PostPageByPageIDParams) ([]PostPageByPageIDRow, error) {
	rows, err := q.db.Query(ctx, postPageByPageID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PostPageByPageIDRow
	for rows.Next() {
		var i PostPageByPageIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.UserID,
			&i.CommentsCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const postPagesAfterPostID = `-- name: PostPagesAfterPostID :many
SELECT id, title, content, user_id, comments_count, created_at
FROM posts
WHERE id > $1
ORDER BY id DESC LIMIT $2
`

type PostPagesAfterPostIDParams struct {
	ID    int32
	Limit int32
}

type PostPagesAfterPostIDRow struct {
	ID            int32
	Title         string
	Content       string
	UserID        int32
	CommentsCount int32
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) PostPagesAfterPostID(ctx context.Context, arg PostPagesAfterPostIDParams) ([]PostPagesAfterPostIDRow, error) {
	rows, err := q.db.Query(ctx, postPagesAfterPostID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PostPagesAfterPostIDRow
	for rows.Next() {
		var i PostPagesAfterPostIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.UserID,
			&i.CommentsCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const postPagesBeforePostID = `-- name: PostPagesBeforePostID :many
SELECT id, title, content, user_id, comments_count, created_at
FROM posts
WHERE id < $1
ORDER BY id DESC LIMIT $2
`

type PostPagesBeforePostIDParams struct {
	ID    int32
	Limit int32
}

type PostPagesBeforePostIDRow struct {
	ID            int32
	Title         string
	Content       string
	UserID        int32
	CommentsCount int32
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) PostPagesBeforePostID(ctx context.Context, arg PostPagesBeforePostIDParams) ([]PostPagesBeforePostIDRow, error) {
	rows, err := q.db.Query(ctx, postPagesBeforePostID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PostPagesBeforePostIDRow
	for rows.Next() {
		var i PostPagesBeforePostIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.UserID,
			&i.CommentsCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const postTagInsert = `-- name: PostTagInsert :exec
INSERT INTO post_tags (post_id, tag) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type PostTagInsertParams struct {
	PostID int32
	Tag    string
}

func (q *Queries) PostTagInsert(ctx context.Context, arg PostTagInsertParams) error {
	_, err := q.db.Exec(ctx, postTagInsert, arg.PostID, arg.Tag)
	return err
}

const userCreate = `-- name: UserCreate :one
INSERT INTO users (name, email)
VALUES ($1, $2)
RETURNING id, name, email, avatar_url, created_at
`

type UserCreateParams struct {
	Name  string
	Email string
}

type UserCreateRow struct {
	ID        int32
	Name      string
	Email     string
	AvatarUrl pgtype.Text
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) UserCreate(ctx context.Context, arg UserCreateParams) (UserCreateRow, error) {
	row := q.db.QueryRow(ctx, userCreate, arg.Name, arg.Email)
	var i UserCreateRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const userGet = `-- name: UserGet :one
SELECT id, name, email, avatar_url, created_at
FROM users
WHERE id = $1
`

type UserGetRow struct {
	ID        int32
	Name      string
	Email     string
	AvatarUrl pgtype.Text
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) UserGet(ctx context.Context, id int32) (UserGetRow, error) {
	row := q.db.QueryRow(ctx, userGet, id)
	var i UserGetRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const userGetByNameOrEmail = `-- name: UserGetByNameOrEmail :many
SELECT name, email
FROM users
WHERE name = $1 OR email = $2
`

type UserGetByNameOrEmailParams struct {
	Name  string
	Email string
}

type UserGetByNameOrEmailRow struct {
	Name  string
	Email string
}

func (q *Queries) UserGetByNameOrEmail(ctx context.Context, arg UserGetByNameOrEmailParams) ([]UserGetByNameOrEmailRow, error) {
	rows, err := q.db.Query(ctx, userGetByNameOrEmail, arg.Name, arg.Email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserGetByNameOrEmailRow
	for rows.Next() {
		var i UserGetByNameOrEmailRow
		if err := rows.Scan(&i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userGetNameById = `-- name: UserGetNameById :one
SELECT name
FROM users
WHERE id = $1
`

func (q *Queries) UserGetNameById(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRow(ctx, userGetNameById, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const userUpdate = `-- name: UserUpdate :one
UPDATE users
SET name = $1, email = $2
WHERE id = $3
RETURNING id, name, email, avatar_url, created_at
`

type UserUpdateParams struct {
	Name  string
	Email string
	ID    int32
}

type UserUpdateRow struct {
	ID        int32
	Name      string
	Email     string
	AvatarUrl pgtype.Text
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) UserUpdate(ctx context.Context, arg UserUpdateParams) (UserUpdateRow, error) {
	row := q.db.QueryRow(ctx, userUpdate, arg.Name, arg.Email, arg.ID)
	var i UserUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}
